version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    volumes:
      - ./mssql/data:/var/opt/mssql/data
      - ./mssql/log:/var/opt/mssql/log
#同步容器時區 (限Linux容器)
#      - /etc/localtime:/etc/localtime:ro
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd
    restart: always
    container_name: mssql

  microsoft-graph-bot:
    image: ntutselab/microsoft-graph-bot:latest
    volumes:
      - ./bot/appsettings.json:/app/appsettings.json
      - ./bot/Logs:/app/Logs
#同步容器時區 (限Linux容器)
#      - /etc/localtime:/etc/localtime:ro
    restart: always
    container_name: MGBot
    depends_on:
      - mssql
